baseURL = "http://www.nullagent.com/"
languageCode = "en-us"
title = "nullagent - Blog"
theme        = "hello-friend-ng"
paginate     = 10
publishDir = "docs/"

[author]
 name = "nullagent"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"



  # Subtitle for home
  homeSubtitle = "Open Source Hacker"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you linke
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "nullagent's homepage"
  keywords = "homepage, blog"
  images = [""]

  # Default theme "light" or "dark"
  defaultTheme = "dark"

  [[params.social]]
    name = "github"
    url  = "https://github.com/sevenbitbyte"
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/nullagent"
  [[params.social]]
    name = "mastodon"
    url  = "https://partyon.xyz/@nullagent"
  [[params.social]]
    name = "instagram"
    url  = "https://instagram.com/nullagent"
  [[params.social]]
    name = "youtube"
    url  = "https://www.youtube.com/@nullagent-hacks"


[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "nullagent"
    subtitle = "Open Source Hacker2"
    keywords = ""
    copyright = 'All rights reserved'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "nullagent"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"
